version: "3.7"

services:

  cypress-dgt:
    build:
      context: .
    image: cypress-dgt
    env_file:
     - .env
    volumes:
      - type: bind
        source: ./
        target: /home/appuser/cypress-dgt