name: build-test-push-deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{github.sha}}

jobs:
  build-test-push:
  # Builds the images, test the code, and push the image to AWS ECR repository.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Image
        run: |
          docker build -t 665952734533.dkr.ecr.eu-west-1.amazonaws.com/cypress-dgt:$IMAGE_TAG

      - name: Push Image to ECR
        run: |
         docker push ${{steps.login-ecr.outputs.registry}}/cypress-dgt:$IMAGE_TAG

      - name: Logout of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
